version: '3.8'

services:
  api:
    build: .
    container_name: spring_nsia_api
    ports:
      - "8081:8080"
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/mon_api_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - my_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mon_api_db
    ports:
      - "3307:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
